### ISSUE TITLE
undefined is not a function

### ISSUE THREAD

**Issue by pvinis** [bluelovers/ws-ypx#2]
- I just installed `1.0.5` using `yarn global add ynpx`.
- I then tried to run `ypx jest`. I got an error. Same thing with `ynpx jest` and `ypx` and `ynpx`.

```
$ ynpx jest
/Users/pvinis/.config/yarn/global/node_modules/ynpx/bin/ypx.js:18
let argv = (0, _yargs.default)(inputArgv).parserConfiguration({
                                          ^

TypeError: undefined is not a function
    at Object.<anonymous> (/Users/pvinis/.config/yarn/global/node_modules/ynpx/bin/ypx.js:18:43)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12)
    at internal/main/run_main_module.js:16:11
```

**Comment by bluelovers** [comment]
forgot move yargs into dependencies when update code, t think already fix in https://github.com/bluelovers/ws-ypx/commit/1c00af52db5dfd3383b4763306173f69980a965b

**Comment by pvinis** [comment]
awesome, thanks for the quick response!
