### ISSUE TITLE
Better UX for missing command

### ISSUE THREAD

**Issue by pvinis** [bluelovers/ws-ypx#3]
ypx has a bit more rough output when there is no command found.

```
$ ypx speedtest
yarn add v1.19.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ speedtest@1.1.0
info All dependencies
└─ speedtest@1.1.0
✨  Done in 1.86s.
installed: 2.921s
[16:38:17.845] [DEBUG] [CWD] /Users/pvinis
[16:38:17.866] [DEBUG] [EXEC] speedtest []
Unhandled rejection Error: spawn speedtest ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

```
$ npx speedtest
npx: installed 1 in 1.174s
command not found: speedtest
```

**Comment by bluelovers** [comment]
> ynpx -q speedtest

![image](https://user-images.githubusercontent.com/167966/73377421-fe5cb580-42f9-11ea-90c2-a3c5f62b6bc9.png)

> ynpx speedtest

![image](https://user-images.githubusercontent.com/167966/73377463-0f0d2b80-42fa-11ea-877d-5aa1748e22ee.png)
